stages:
  - sonar
  - build
  - deploy

image: docker:latest
variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ''
services:
  - docker:dind

.before_script_template:
  before_script:
    - apk add --update --no-cache nodejs npm yarn
    - apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
    - python3 -m ensurepip
    - pip3 install awscli
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY " | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $SSH_IP_SERVER  >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
sonarqube-check:
  image: 
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  stage: sonar
  tags:
    - vmogroup
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - sonar-scanner
  allow_failure: true


web:build:
  stage: build
  extends: .before_script_template
  only:
    - develop
  tags:
    - vmogroup
  variables:
    AWS_PROFILE: vmo
  script:
    - echo $CI_COMMIT_SHORT_SHA
    - echo $ECR_REPO_PROD
    # Get env from gitlab env
    - cat $env_PROD >> .env
    - cat .env
    # ECR login
    - echo Logging in to Amazon ECR...
    - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 422520630625.dkr.ecr.ap-northeast-1.amazonaws.com
    # Build image
    - echo Build started on `date`
    - docker pull $ECR_REPO_PROD
    - docker build --cache-from=$ECR_REPO_PROD -t pni_frontend . -f docker/Dockerfile
    - docker tag pni_frontend $ECR_REPO_PROD:latest
    - echo Build completed on `date`
    # Push image
    - echo Pushing the Docker image...
    - docker push $ECR_REPO_PROD:latest


web:deploy:
  stage: deploy
  extends: .before_script_template
  only:
    - develop
  tags:
    - vmogroup
  variables:
    AWS_PROFILE: vmo
  script:
    - ssh -tt -o StrictHostKeyChecking=no $SSH_USER@$SSH_IP_SERVER "aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 422520630625.dkr.ecr.ap-northeast-1.amazonaws.com && cd /home/developer/pni-fe && docker-compose pull && docker-compose up -d"
    - ssh -tt -o StrictHostKeyChecking=no $SSH_USER@$SSH_IP_SERVER "yes | docker image prune --filter 'dangling=true'"
